# Generated by Django 5.0.6 on 2024-05-31 00:10

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "published": "A post that is available to all on the site",
        "draft": "A post that can only be seen by the author",
        "archived": "An older post, available only to logged in users"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
